fix: selenium < 4.10.0
The latest Selenium causes a pre-commit failure with:
boardfarm/lib/common.py:363:13: E1123:
Unexpected keyword argument 'firefox_profile' in constructor call
(unexpected-keyword-arg)

Change-Id: I2affd94ee47faaa50283237ce74582612e4135cd
Signed-off-by: Michele Gualco <msalvatoregualco@libertyglobal.com>
Reviewed-on: http://10.64.38.13:8080/gerrit/c/github/boardfarm/+/1191
Reviewed-by: Filippo Carra <fcarra@libertyglobal.com>
Tested-by: Filippo Carra <fcarra@libertyglobal.com>