devices: cougarpark: fix error with log
Fixes this issues:

Traceback (most recent call last):
  File "./bft", line 432, in <module>
    main()
  File "./bft", line 290, in main
    clog.write(console.log)
AttributeError: 'spawn' object has no attribute 'log'

All DUTs need to inherit from base device type, including secondary
consoles.

Signed-off-by: Matthew McClintock <msm-oss@mcclintock.net>