bft: enclose all zehpyr execution in try/except
Avoids the following which causes bft to exit:

Starting Zephyr Execution....
Traceback (most recent call last):
  File "./bft", line 441, in <module>
    main()
  File "./bft", line 411, in main
    test_cases_list[tc].append(test_case)
IndexError: list index out of range

Signed-off-by: Matthew McClintock <msm-oss@mcclintock.net>