Fix 'Failed to run ... parse' message
Just listing tests using "./bft -l" printed an error message at top:

    Failed to run <class 'tests.cdrouter_bootstrap.CDrouterCustom'> parse function!

Due to this:

    Traceback (most recent call last):
      File "/home/mikea/boardfarm/tests/__init__.py", line 50, in init
        new_tests = test.parse(config) or []
      File "/home/mikea/boardfarm/tests/lib/common.py", line 33, in wrapper
        return f(*args, **kwargs)
      File "/home/mikea/boardfarm/tests/cdrouter_bootstrap.py", line 329, in parse
        if 'cdrouter_server' in config.board:
    AttributeError: 'module' object has no attribute 'board'

This code change fixes that.

Signed-off-by: Mike Anderson <mbanderson@uwalumni.com>
Change-Id: Ia137074d555ec8b387b2fd889b1e1c36c0fc51a2