devices/debian: Use six.text_type() instead of decode()
In Python3, decode() raises an exception:

    AttributeError: 'str' object has no attribute 'decode'

It looks like the goal was to create a unicode string. So
to support Python2 and Python3 use six.text_type() because
in python2 that will convert to unicode. In python3 it does
nothing.

Signed-off-by: Mike Anderson <mbanderson@uwalumni.com>
Change-Id: Idc52a10d30c76565701753440327204effb4cfb9
Reviewed-on: https://cicd.lgirdk.com/gerrit/c/github/boardfarm/+/2196
Tested-by: Jenkins Automation <jenkins@libertyglobal.com>
Reviewed-by: Matthew McClintock <matthew@meldnetworks.com>